### ISSUE TITLE
Face landmark in smaller AVCaptureVideoPreviewLayer

### ISSUE THREAD

**Issue by davnag** [Weijay/AppleFaceDetection#3]
Hi, thank you for a great example!

I'm trying to do this in a smaller view but can´t figure out how to calculate the new Face landmark frames.

Say that I have a smaller AVCaptureVideoPreviewLayer say in a CGRect(x: 0, y: 44, width: 320, height: 300). I get face landmarks like this.

Do you have any idé how I can accomplish this?

![img_6078e6f6106f-1](https://user-images.githubusercontent.com/12034780/42519946-5e642d00-8465-11e8-9b9a-a8d8e23e1a75.jpeg)

**Comment by Willjay90** [comment]
The `VNFaceObservation` returns a normalized bounding box. You have to do the math for translation according to size of your layer. For example, I just use the `frame.width` and `frame.height` of my Preview.
        
        func drawFaceWithLandmarks(face: VNFaceObservation) {
        
            let transform = CGAffineTransform(scaleX: 1, y: -1).translatedBy(x: 0, y: -frame.height)
        
            let translate = CGAffineTransform.identity.scaledBy(x: frame.width, y: frame.height)
        
            // The coordinates are normalized to the dimensions of the processed image, with the origin at the image's lower-left corner.
            let facebounds = face.boundingBox.applying(translate).applying(transform)
           ...

**Comment by davnag** [comment]
I'm still having problem with this and I think its because the videoGravity property I have to change on AVCaptureVideoPreviewLayer. 

I made a smaller preview view and changed `.videoGravity` on `videoPreviewLayer`
<img width="246" alt="image" src="https://user-images.githubusercontent.com/12034780/42728593-ec077bde-87bd-11e8-8a88-6c000bb18882.png">

```swift
var videoPreviewLayer: AVCaptureVideoPreviewLayer {
   let videoLayer = layer as! AVCaptureVideoPreviewLayer
   videoLayer.videoGravity = .resizeAspectFill
   return videoLayer
}
```

If you have the time could you please check the changes I made on this fork.
https://github.com/davnag/AppleFaceDetection
