### ISSUE TITLE
Issue while Drawing boudning box in front camera.

### ISSUE THREAD

**Issue by ERbittuu** [Weijay/AppleFaceDetection#5]
The bounding box around the user's face does not follow him/her correctly. The x position gets reversed somehow. When one moves their face to the left the bounding box goes to the right.
![img_82fc36f47ecb-1](https://user-images.githubusercontent.com/19172785/52324512-9554a180-2a07-11e9-870c-4532fc503169.jpeg)

**Comment by Willjay90** [comment]
Thanks for letting me know. Fix it with the latest commit.

**Comment by ERbittuu** [comment]
Thank you
